# Generated by Django 2.2.1 on 2019-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
