# Generated by Django 2.2.1 on 2019-05-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_songs_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
