# Generated by Django 2.2.1 on 2019-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190527_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.FileField(upload_to='D:\\Projects\\Django\\BeatabelAPI\\songs'),
        ),
    ]
