# Generated by Django 2.2.1 on 2019-06-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_song_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='path',
        ),
    ]
